---
name: Fx.Spring
author: clau
category: Effects
tags: [Effects, Animation, Transition, Fx, Spring, Physics]
docs: http://tabqwerty.com/2010/06/11/rethink-animation.html
demo: http://tabqwerty.com/2010/06/11/rethink-animation.html
current: 0.1